braiins-os: Create bos_plus package for upgrading to BOS+
- add system package 'bos_plus' with script for downloading firmware
  from external feed server
- fix original 'firmware' package to exit when wget fails

diff --git a/braiins-os/package/system/bos_plus/Makefile b/braiins-os/package/system/bos_plus/Makefile
--- a/braiins-os/package/system/bos_plus/Makefile
+++ b/braiins-os/package/system/bos_plus/Makefile
@@ -23,42 +23,35 @@
 include $(TOPDIR)/rules.mk
 include $(INCLUDE_DIR)/kernel.mk
 
-PKG_NAME:=firmware
-PKG_MAINTAINER:=Braiins <braiins@braiins.com>
+PKG_NAME:=bos_plus
+PKG_RELEASE:=1
 
-# set firmware version
-PKG_RELEASE:=$(call qstrip,$(CONFIG_FIRMWARE_VERSION))
+PKG_MAINTAINER:=Braiins <braiins@braiins.com>
 
 BOS_FEEDS_SERVER:=https://feeds.braiins-os.org/$(SUBTARGET)
 BOS_FEEDS_CONFIG:=/etc/opkg/bosfeeds.conf
 
 include $(INCLUDE_DIR)/package.mk
 
-define Package/firmware
+define Package/bos_plus
   SECTION:=utils
   CATEGORY:=Utilities
-  TITLE:=Current Firmware
+  TITLE:=Upgrade to BOS+
 endef
 
-define Package/firmware/description
- Meta package for automated firmware upgrades.
-endef
-
-define Package/firmware/config
-	source "$(SOURCE)/Config.in"
+define Package/bos_plus/description
+ Meta package for firmware upgrade to BOS+.
 endef
 
 define Build/Compile
 endef
 
-define Package/firmware/install
+# LEDE requires some data for installation
+define Package/bos_plus/install
 	$(INSTALL_DIR) $(1)/etc
-	$(INSTALL_CONF) ./files/fw_info.json $(1)/etc/
-	$(INSTALL_DIR) $(1)/etc/opkg
-	echo "src/gz bos_firmware $(BOS_FEEDS_SERVER)" > $(1)$(BOS_FEEDS_CONFIG)
 endef
 
-define Package/firmware/preinst
+define Package/bos_plus/preinst
 #!/bin/sh
 
 # if run within buildroot exit
@@ -76,27 +69,18 @@ fi
 PACKAGES_NAME="Packages"
 PACKAGES_PATH="/tmp/$${PACKAGES_NAME}"
 SYSUPGRADE_PATH="/tmp/sysupgrade.tar"
-BOS_FEEDS="$(BOS_FEEDS_CONFIG)"
-BOS_FEEDS_RECORD="bos_firmware"
-FIRMWARE_NAME="$(PKG_NAME)_$(VERSION)_$(PKGARCH).tar"
-FIRMWARE_REQUIRE="$(call qstrip,$(CONFIG_FIRMWARE_REQUIRE))"
+BOS_FEEDS="/etc/bosplusfeeds.conf"
 
 if [ ! -f "$${BOS_FEEDS}" ]; then
-	# fallback for old miner firmwares
-	BOS_FEEDS="/etc/opkg/minerfeeds.conf"
-	BOS_FEEDS_RECORD="miner_firmware"
-fi
-if [ ! -f "$${BOS_FEEDS}" ]; then
-	echo "Missing configuration file $(BOS_FEEDS_CONFIG)!" >&2
+	echo "Missing configuration file $${BOS_FEEDS}!" >&2
 	exit 1
 fi
 
 # parse server address from opkg configuration file
-feeds_server=$$(awk '/'$${BOS_FEEDS_RECORD}'/ {print $$3}' "$${BOS_FEEDS}")
+feeds_server=$$(cat "$${BOS_FEEDS}")
 
 if [ -z "$${feeds_server}" ]; then
 	echo "Cannot find feeds server in $${BOS_FEEDS}!" >&2
-	echo "Configuration with '$${BOS_FEEDS_RECORD}' is probably missing." >&2
 	exit 1
 fi
 
@@ -108,6 +92,13 @@ current_fw_version() {
 	fi
 }
 
+latest_fw_version() {
+	result=$$(awk '/Package: /{p=$$2} /Version: /{v=$$2} /Require: /{r=$$2} \
+		/Filename: /{if (p == "firmware") print $$2" "r}' "$$1" | tail -n1)
+	eval $$2=$${result% *}
+	eval $$3=$${result#* }
+}
+
 required_fw_version() {
 	result=$$(awk '/Package: /{p=$$2} /Version: /{v=$$2} /Require: /{r=$$2} \
 		/Filename: /{if (p == "firmware" && v == "'$$2'") print $$2" "r}' "$$1")
@@ -116,20 +107,21 @@ required_fw_version() {
 }
 
 get_firmware_name() {
-	local fw_version=$$(current_fw_version)
-	local require=$${FIRMWARE_REQUIRE}
-	local filename=$${FIRMWARE_NAME}
-	if [ ! "$${fw_version}" "<" "$${require}" ]; then
-		eval $$1=$${filename}
-		return 0
-	fi
-
 	echo "Downloading package list..."
 	wget -O "$${PACKAGES_PATH}.gz" "$${feeds_server}/$${PACKAGES_NAME}.gz" || return 1
 	gzip -df "$${PACKAGES_PATH}.gz" || return 1
 	wget -O "$${PACKAGES_PATH}.sig" "$${feeds_server}/$${PACKAGES_NAME}.sig" || return 1
 	echo "Checking signature..."
 	usign -V -m "$${PACKAGES_PATH}" -P "/etc/opkg/keys" || return 1
+
+	local fw_version=$$(current_fw_version)
+	local filename
+	local require
+	latest_fw_version "$${PACKAGES_PATH}" filename require
+	if [ ! "$${fw_version}" "<" "$${require}" ]; then
+		eval $$1=$${filename}
+		return 0
+	fi
 
 	while [ "$${fw_version}" "<" "$${require}" ]; do
 		required_fw_version "$${PACKAGES_PATH}" $${require} filename require
@@ -144,7 +136,6 @@ if get_firmware_name firmware_name; then
 	wget -O "$${SYSUPGRADE_PATH}" "$${feeds_server}/$${firmware_name}" || exit 1
 	sysupgrade "$${SYSUPGRADE_PATH}"
 else
-	echo "Firmware version '$${FIRMWARE_REQUIRE}' is required before upgrading to this version." >&2
 	echo "Cannot find required firmware on server!" >&2
 	exit 1
 fi
@@ -155,35 +146,4 @@ sleep 10
 exit 2
 endef
 
-define Package/firmware/prerm
-#!/bin/sh
-
-. /lib/functions/bos-defaults.sh
-
-# check if package is being removed in NAND mode
-if [ $$BOS_MODE != 'nand' ]; then
-	echo "Firmware cannot be installed/removed in '$$BOS_MODE' mode!"
-	echo "This functionality is available only for system running from NAND."
-	if [ $$BOS_MODE == 'sd' ]; then
-		echo
-		echo "Please read documentation about installation of current system to NAND from SD card."
-	fi
-	echo
-	exit 1
-fi
-endef
-
-define Package/firmware/postrm
-#!/bin/sh
-
-. /lib/functions/bos-defaults.sh
-
-# do not call factory reset when package removal has been forced for incorrect mode
-[ $$BOS_MODE == 'nand' ] || exit 1
-
-# if this script is run then simple package remove has been called
-echo "Processing factory reset..."
-bos factory_reset
-endef
-
-$(eval $(call BuildPackage,firmware))
+$(eval $(call BuildPackage,bos_plus))
